// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-fRwKxlPNBnmXidU0s1c1Ptg7YG0Bnj8',
    appId: '1:1024583763986:web:114ecfb750bd78c70e70cb',
    messagingSenderId: '1024583763986',
    projectId: 'cooktoghether-51274',
    authDomain: 'cooktoghether-51274.firebaseapp.com',
    storageBucket: 'cooktoghether-51274.appspot.com',
    measurementId: 'G-LGFHJP8J3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29h4iuPqWSlDW3_T500ljJV9M-tQFx_Q',
    appId: '1:1024583763986:android:8dbcf11d7bdb452f0e70cb',
    messagingSenderId: '1024583763986',
    projectId: 'cooktoghether-51274',
    storageBucket: 'cooktoghether-51274.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBugqRPkugr2wflt4K6gFhXP7zY-00H53c',
    appId: '1:1024583763986:ios:f177c4018d7942860e70cb',
    messagingSenderId: '1024583763986',
    projectId: 'cooktoghether-51274',
    storageBucket: 'cooktoghether-51274.appspot.com',
    iosBundleId: 'com.example.cookTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBugqRPkugr2wflt4K6gFhXP7zY-00H53c',
    appId: '1:1024583763986:ios:f177c4018d7942860e70cb',
    messagingSenderId: '1024583763986',
    projectId: 'cooktoghether-51274',
    storageBucket: 'cooktoghether-51274.appspot.com',
    iosBundleId: 'com.example.cookTogether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-fRwKxlPNBnmXidU0s1c1Ptg7YG0Bnj8',
    appId: '1:1024583763986:web:88dd90f09e6218b30e70cb',
    messagingSenderId: '1024583763986',
    projectId: 'cooktoghether-51274',
    authDomain: 'cooktoghether-51274.firebaseapp.com',
    storageBucket: 'cooktoghether-51274.appspot.com',
    measurementId: 'G-N5KLQ5V4N1',
  );
}
